# Generated by Django 4.1.2 on 2022-10-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titlname',
            new_name='name',
        ),
    ]
